#!/bin/sh

#Host pkg-config script to run on x86, targeting armv7a
#Tested on pkg-config 0.23 (from arm-arago-linux TI)
#Tested on pkg-config 0.25 (from arm-linux linaro)
#Will not work on pkg-config 0.22 (from 10.04)
export UBUNTU_CORE_ROOTFS=/home/prabindh/work1/ubuntu-core/media/rootfs
#unset this first then set libdir correctly
export PKG_CONFIG_DIR=
export PKG_CONFIG_LIBDIR=${UBUNTU_CORE_ROOTFS}/usr/lib/arm-linux-gnueabi/pkgconfig:${UBUNTU_CORE_ROOTFS}/usr/share/pkgconfig
export PKG_CONFIG_SYSROOT_DIR=${UBUNTU_CORE_ROOTFS}/usr
#Below is needed for 0.25
export PKG_CONFIG_PATH=${UBUNTU_CORE_ROOTFS}/usr/lib/arm-linux-gnueabi/pkgconfig:${UBUNTU_CORE_ROOTFS}/usr/share/pkgconfig
/opt/linaro/gcc-linaro-arm-linux-gnueabi-2012.03-20120326_linux/bin/arm-linux-gnueabi-pkg-config --define-variable=prefix=${UBUNTU_CORE_ROOTFS}/usr "$@"

#/opt/toolchain-4.5.3-dynamic/arago-2011.09/armv7a/bin/pkg-config "$@"

